version: "3.4"

services:
  ms-unfollows:
    container_name: ms-unfollows
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./config.env
    environment:
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - TWITTER_API_KEY
      - TWITTER_API_SECRET_KEY
    links:
      - unfollows-redis
    command: ./wait-for.sh -t 60 unfollows-redis:6379 -- python service.py show

  unfollows-redis:
    container_name: unfollows-redis
    image: redis:6-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 4n_ins3cure_P4ss
    expose:
      - 6379
    volumes:
      - unfollows_redis_data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
      #- $PWD/dump.rdb:/data/dump.rdb
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  unfollows_redis_data:
